lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

fix: whitelist addEventListener and few SVG attributes

---

README.md
lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

feat: add ignoreAttribute option

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

Add more common attributes and functions to the lists and add tests around those + add tests to make sure attributes for accessibility are not ignored.

feat: add more ignored attributes and callee

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

Allow displayName property in classes

---

README.md
lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

Add the ability to ignore specific properties in an object. Prevents the need to use dynamic property assignment with capitalized variable names in some cases.
Thanks!

Add "ignoreProperty" option

---

README.md
lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

Ignores literals within the `Trans` element, which is added by default as it is part of `react-i18next`.
Thanks!

Ignore Trans element

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

allow user to ignore strings or callee by regular expression
BREAKING CHANGE: all patterns in ignoreCallee would be treated as regular expression
fix #19

feat: allow regex in ignore and ignoreCallee

---

README.md
lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

we needed this for an icon component that retrieves string literals. thought it might be useful.

feat: allow ignoring lists of components

---

README.md
lib/helper.js
lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

feat: add onlyAttribute option

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

feat: ignore UPPER_CASE arrays

---

README.md
lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

Validate template strings

---

.prettierrc
CHANGELOG.md
lib/rules/no-literal-string.js
package-lock.json
package.json
tests/lib/rules/no-literal-string.js

Validate template

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

fix: ignore strings as object property name

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string.js

fix: drop wrong ts supports

---

lib/options/schema.json

Allow regexp in include/exclude.

---

lib/rules/no-literal-string.js
tests/lib/fixtures/valid.jsx
tests/lib/rules/no-literal-string/words.js

feat: treat template literals without expressions as normal strings

---

lib/helper/index.js
tests/lib/fixtures/invalid.jsx
tests/lib/rules/no-literal-string/all.js
tests/lib/rules/no-literal-string/callees.js
tests/lib/rules/no-literal-string/default.js

fix: check title attribute in dom elements

---

v5.md

I added a couple of comments. I think they will make it easier for those who have just started learning about "eslint-plugin-i18next".

feat: add comments for a better user experience for beginners

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string/should-validate-template.js

feat: allow to ignore tag template via callees

---

lib/rules/no-literal-string.js
tests/lib/fixtures/valid-typescript.ts

feat: ignore hand-written literal type

---

lib/index.d.ts
lib/index.js
package.json

This PR adds some basic type definitions in order to improve compatibility with the new flat config format (see https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2246 for more details on that).

feat: add type definitions

---

lib/rules/no-literal-string.js
tests/lib/rules/no-literal-string/jsx-components.js

feat: support to filter jsx component named like A.B
